Stat svc
gyngazov/java-explore-with-me pull request #3
Opened 2023-08-22 14:40 UTC by gyngazov

2023-08-24 07:33 UTC, gyngazov commented
постман тесты
https://github.com/gyngazov/java-explore-with-me/blob/stat_svc/statistics/server/src/test/resources/statsPostmanCollection.json

2023-08-24 18:09 UTC, EugeneLenkevich requested changes
Привет, Лев, спасибо за PR

Отличная работа, спасибо, пара косметических моментиков, посмотри коментарии, пожалуйста :)

2023-08-24 18:09 UTC, EugeneLenkevich commented on pom.xml
> +	<!--profiles>
Давай ка все же почикаем закоментированный код, для истории есть гит, а вот внешний вид такой код портит :)

2023-08-25 11:05 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2023-08-25 12:10 UTC, merged