Main svc
gyngazov/java-explore-with-me pull request #4
Opened 2023-09-08 12:10 UTC by gyngazov

2023-09-10 09:21 UTC, EugeneLenkevich requested changes
Привет, Лев! Спасибо за PR.

В целом все отлично :)
Есть совсем небольшие пометки, посмотри комментарии ниже, пожалуйста

2023-09-10 09:21 UTC, EugeneLenkevich commented on events/src/main/java/ru/practicum/explorewithme/AbstractService.java
> +    default Pageable getPage(String sort, int from, int size) {
Можно было бы кстати сделать и абстрактный класс. 
Интерфейс - это все таки контракт в первую очередь, он должен быть без логики. А эти default-методы - это больше костыль для обратной совместимости или каких то других специфических случаев :)

2023-09-10 09:21 UTC, EugeneLenkevich commented on events/src/main/java/ru/practicum/explorewithme/EntityAdapter.java
> +            throw new ConflictException("Integrity constraint has been violated.", ve.getMessage());
А что если в лог сразу писать сразу оригинальную ошибку плюс можно какую то отладочную информацию добавить, id сущности например :)

2023-09-10 09:21 UTC, EugeneLenkevich commented on events/src/main/java/ru/practicum/explorewithme/category/CategoryController.java
> +    public static final String DEFAULT_PAGE = "10";
А что если в проперти это значение засунуть :)

![image](https://github.com/gyngazov/java-explore-with-me/assets/109306643/66db831b-5326-41ab-b199-141308886ee0)

https://stackoverflow.com/questions/30528255/how-to-access-a-value-defined-in-the-application-properties-file-in-spring-boot

2023-09-10 09:21 UTC, EugeneLenkevich commented on events/src/main/java/ru/practicum/explorewithme/category/CategoryService.java
> +    public CategoryDto add(CategoryNew categoryNew) {
А давай ка еще над все методы, которые изменяют данные (insert, update и delete) будем оформлять как логические транзакции, так будет правильнее. То есть добавим аннотацию @Transactional над ними

2023-09-10 09:21 UTC, EugeneLenkevich commented on events/src/main/java/ru/practicum/explorewithme/category/CategoryService.java
> +        } catch (DataIntegrityViolationException ve) {
Ммм, а зачем было заводить всякие дополнительные классы и интерфейсы если в итоге все равно в сервисах перехватываем исключения, может тут имеет место быть некоторое переусложнение или нет? :)

2023-09-10 09:21 UTC, EugeneLenkevich commented on events/src/main/java/ru/practicum/explorewithme/compilation/CompilationServiceImpl.java
> +    EventShortMapper esm = new EventShortMapper();
А почему бы тоже бином не сделать, для единообразия :)

2023-09-10 09:21 UTC, EugeneLenkevich commented on events/src/main/java/ru/practicum/explorewithme/compilation/CompilationServiceImpl.java
> +        for (Event e: events) {
Модно кстати разом сохранять коллекцию, метод saveAll в репозитории, работает более эффективно чем n-отдельных запросов :)

2023-09-10 09:25 UTC, EugeneLenkevich requested changes
.

2023-09-11 11:21 UTC, EugeneLenkevich commented
>> Евгений, я подправил по замечаниям. Но тест на гитхабе висит уже пол часа... Можно мне перейти к этапу 3 ? А то не известно, сколько прожду еще, и потом не уложусь до 15.09 ...

За красные тесты заругают. Спроси наставника что там не так, не понятно по логу)

2023-09-11 11:50 UTC, gyngazov commented
https://app.pachca.com/chats?thread_id=1925584
на null в ответе повисало

2023-09-11 13:12 UTC, gyngazov commented
Не разобрался с дефолтной странице в настройку.
При:
@Value("${default.page.size}$")
private String defaultPage;
получаю Attribute value must be constant

2023-09-11 14:41 UTC, gyngazov commented
Дефолтную страницу сделал через конфиг.

2023-09-11 17:28 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2023-09-12 06:33 UTC, gyngazov commented
Спасибо, за ревью!

2023-09-12 06:33 UTC, merged